import type { AtlasEntry } from "./types";

export const atlasEntries: AtlasEntry[] = [
  {
    id: "medina",
    topic: "bifurcation",
    title: "Medina Bifurcation Classification",
    source: "Interventional Cardiology 8e",
    chapter: "Ch 23",
    page: "p506",
    image: "/images/bifurcation/medina-classification.png",
    tags: ["classification", "Medina", "bifurcation"],
  },
  {
    id: "provisional-algo",
    topic: "bifurcation",
    title: "Provisional Stenting Algorithm",
    source: "Interventional Cardiology 8e",
    chapter: "Ch 23",
    page: "p509",
    image: "/images/bifurcation/provisional-algorithm.png",
    tags: ["provisional", "algorithm", "POT", "FKBI"],
  },
  {
    id: "crush-culotte",
    topic: "bifurcation",
    title: "Crush vs Culotte Techniques",
    source: "Interventional Cardiology 8e",
    chapter: "Ch 23",
    page: "p513",
    image: "/images/bifurcation/crush-culotte.png",
    tags: ["crush", "culotte", "two-stent", "TAP"],
  },
  {
    id: "crush-example",
    topic: "bifurcation",
    title: "Crush Technique — Angiographic Example",
    source: "Interventional Cardiology 8e",
    chapter: "Ch 23",
    page: "p515",
    image: "/images/bifurcation/crush-example.png",
    tags: ["crush", "angiogram"],
  },
  {
    id: "multivessel",
    topic: "bifurcation",
    title: "Multivessel PCI Strategy",
    source: "Interventional Cardiology 8e",
    chapter: "Ch 19",
    page: "p417",
    image: "/images/bifurcation/multivessel-strategy.png",
    tags: ["multivessel", "staging", "syntax"],
  },
  {
    id: "kern-pci",
    topic: "bifurcation",
    title: "PCI Overview & Equipment",
    source: "Kern's 7e",
    chapter: "Ch 6",
    page: "p384",
    image: "/images/bifurcation/kern-pci-overview.png",
    tags: ["equipment", "DAPT", "stents"],
  },
  {
    id: "jailed-ffr",
    topic: "ffr",
    title: "Jailed Side Branch — FFR Physiology",
    source: "Interventional Cardiology 8e",
    chapter: "Ch 5",
    page: "p142",
    image: "/images/ffr/jailed-sb-ffr.png",
    tags: ["FFR", "jailed", "side branch"],
  },
  {
    id: "ffr-algo",
    topic: "ffr",
    title: "FFR-Guided Side Branch Management",
    source: "Interventional Cardiology 8e",
    chapter: "Ch 5",
    page: "p142–146",
    image: "/images/ffr/ffr-algorithm.png",
    tags: ["FFR", "algorithm", "iFR"],
  },
  {
    id: "third-degree",
    topic: "bradyarrhythmia",
    title: "Third Degree AV Block",
    source: "Braunwald 12e",
    chapter: "Ch 50",
    page: "p1451",
    image: "/images/chb/third-degree-avb.png",
    tags: ["CHB", "complete heart block", "AV block"],
  },
  {
    id: "chb-management",
    topic: "bradyarrhythmia",
    title: "Bradyarrhythmia Management Algorithm",
    source: "Braunwald 12e",
    chapter: "Ch 50",
    page: "p1454",
    image: "/images/chb/management-algorithm.png",
    tags: ["management", "pacing", "algorithm"],
  },
  {
    id: "stemi-avb",
    topic: "bradyarrhythmia",
    title: "AV Block in STEMI",
    source: "Braunwald 12e",
    chapter: "Ch 35",
    page: "p879",
    image: "/images/chb/stemi-avb-table.png",
    tags: ["STEMI", "inferior MI", "recovery"],
  },
  {
    id: "topol-chb",
    topic: "bradyarrhythmia",
    title: "Clinical Presentation of 3rd Degree AV Block",
    source: "Topol 5e",
    chapter: "Ch 22",
    page: "p286",
    image: "/images/chb/topol-presentation.png",
    tags: ["presentation", "symptoms"],
  },
  {
    id: "pacing-indications",
    topic: "bradyarrhythmia",
    title: "Pacemaker Indications",
    source: "Kern's 7e",
    chapter: "Ch 7 EP Lab",
    page: "p456",
    image: "/images/chb/pacing-indications.png",
    tags: ["PPM", "indications", "guidelines"],
  },
  {
    id: "temp-pacing",
    topic: "bradyarrhythmia",
    title: "Temporary Transvenous Pacing",
    source: "Topol 5e",
    chapter: "Ch 57",
    page: "p704",
    image: "/images/chb/temp-pacing.png",
    tags: ["temporary pacing", "transvenous"],
  },
];
